# syntax=docker/dockerfile:1.7


# =============================================================
# BASE
# =============================================================

FROM node:22-alpine AS base

WORKDIR /app

RUN corepack enable


# =============================================================
# DEPENDENCIES
# =============================================================

FROM base AS deps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

# Do not run postinstall here because the application source
# has not been copied into this stage yet.
RUN pnpm install \
    --frozen-lockfile \
    --ignore-scripts


# =============================================================
# BUILDER
# =============================================================

FROM base AS builder

COPY --from=deps /app/node_modules ./node_modules

COPY . .


# =============================================================
# RUN PROJECT POSTINSTALL STEP
# =============================================================

RUN pnpm run export-css


# =============================================================
# CACHE BUSTER
#
# BuildKit secrets do not participate in the cache key.
# GitHub passes GITHUB_SHA here so the application build is
# forced to execute again for each commit.
# =============================================================

ARG CACHEBUST=1


# =============================================================
# BUILD APPLICATION
#
# BUILD_ENV is a JSON BuildKit secret generated by GitHub.
#
# DATABASE_URI should already have been converted from:
#
#   mongodb://...@[DB_HOST]:[DB_PORT]/...
#
# to:
#
#   mongodb://...@host.docker.internal:27018/...
#
# This stage verifies:
#
#   1. BUILD_ENV is valid JSON
#   2. DATABASE_URI exists
#   3. DATABASE_URI host is host.docker.internal
#   4. DATABASE_URI has a valid port
#   5. host.docker.internal resolves inside THIS build
#   6. THIS build can connect to the database tunnel
#   7. All BUILD_ENV values are passed to pnpm build
#
# No database credentials are printed.
# =============================================================

RUN --mount=type=secret,id=BUILD_ENV,required=true \
    node <<'NODE'
const fs = require("fs");
const net = require("net");
const dns = require("dns").promises;
const { spawn } = require("child_process");

async function main() {
  // -----------------------------------------------------------
  // READ BUILD ENVIRONMENT
  // -----------------------------------------------------------

  const secretPath = "/run/secrets/BUILD_ENV";

  if (!fs.existsSync(secretPath)) {
    console.error("ERROR: BUILD_ENV secret was not mounted.");
    process.exit(1);
  }

  let parsed;

  try {
    const raw = fs.readFileSync(secretPath, "utf8");
    parsed = JSON.parse(raw);
  } catch {
    console.error("ERROR: BUILD_ENV does not contain valid JSON.");
    process.exit(1);
  }

  if (
    !parsed ||
    Array.isArray(parsed) ||
    typeof parsed !== "object"
  ) {
    console.error("ERROR: BUILD_ENV must contain a JSON object.");
    process.exit(1);
  }


  // -----------------------------------------------------------
  // CONVERT JSON -> PROCESS ENVIRONMENT
  // -----------------------------------------------------------

  const buildEnv = {};

  for (const [key, value] of Object.entries(parsed)) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      console.error(
        `ERROR: Invalid environment variable name: ${key}`
      );

      process.exit(1);
    }

    if (value === null || value === undefined) {
      buildEnv[key] = "";
    } else if (typeof value === "string") {
      buildEnv[key] = value;
    } else {
      buildEnv[key] = String(value);
    }
  }


  // -----------------------------------------------------------
  // DATABASE_URI MUST EXIST
  // -----------------------------------------------------------

  if (!buildEnv.DATABASE_URI) {
    console.error("ERROR: DATABASE_URI is required.");
    process.exit(1);
  }


  // -----------------------------------------------------------
  // PARSE DATABASE URI
  //
  // Do NOT print the URI because it contains credentials.
  // -----------------------------------------------------------

  let database;

  try {
    database = new URL(buildEnv.DATABASE_URI);
  } catch {
    console.error("ERROR: DATABASE_URI is not a valid URI.");
    process.exit(1);
  }


  // -----------------------------------------------------------
  // VERIFY DATABASE HOST
  // -----------------------------------------------------------

  if (database.hostname !== "host.docker.internal") {
    console.error(
      "ERROR: Docker received the wrong DATABASE_URI hostname."
    );

    process.exit(1);
  }

  console.log(
    "DATABASE_URI hostname verified: host.docker.internal"
  );


  // -----------------------------------------------------------
  // VERIFY DATABASE PORT
  // -----------------------------------------------------------

  const databasePort = Number(database.port);

  if (
    !Number.isInteger(databasePort) ||
    databasePort < 1 ||
    databasePort > 65535
  ) {
    console.error(
      "ERROR: DATABASE_URI contains an invalid database port."
    );

    process.exit(1);
  }

  console.log(
    `DATABASE_URI port verified: ${databasePort}`
  );


  // -----------------------------------------------------------
  // VERIFY HOST.DOCKER.INTERNAL DNS
  //
  // This proves --add-host from docker build actually reached
  // this build container.
  // -----------------------------------------------------------

  let addresses;

  try {
    addresses = await dns.lookup(
      "host.docker.internal",
      {
        all: true,
      }
    );
  } catch (error) {
    console.error(
      "ERROR: host.docker.internal cannot be resolved " +
      "inside the Docker build."
    );

    console.error(
      `DNS error: ${error.code || "UNKNOWN"}`
    );

    process.exit(1);
  }

  if (!addresses.length) {
    console.error(
      "ERROR: host.docker.internal resolved to no addresses."
    );

    process.exit(1);
  }

  console.log(
    "host.docker.internal resolves inside Docker build."
  );


  // -----------------------------------------------------------
  // TEST TCP CONNECTION FROM ACTUAL BUILD CONTAINER
  //
  // Docker build
  //      ↓
  // host.docker.internal
  //      ↓
  // GitHub runner :27018
  //      ↓
  // SSH
  //      ↓
  // VPS temporary socat proxy
  //      ↓
  // MongoDB
  // -----------------------------------------------------------

  await new Promise((resolve, reject) => {
    const socket = net.createConnection({
      host: database.hostname,
      port: databasePort,
    });

    const timeout = setTimeout(() => {
      socket.destroy();

      reject(
        new Error("Database TCP connection timed out.")
      );
    }, 10000);

    socket.once("connect", () => {
      clearTimeout(timeout);

      socket.destroy();

      resolve();
    });

    socket.once("error", (error) => {
      clearTimeout(timeout);

      socket.destroy();

      reject(error);
    });
  }).catch((error) => {
    console.error(
      "ERROR: Docker build cannot reach the database tunnel."
    );

    console.error(
      `Connection error: ${error.code || error.message}`
    );

    process.exit(1);
  });

  console.log(
    "Docker build can reach database tunnel."
  );


  // -----------------------------------------------------------
  // BUILD ENVIRONMENT READY
  // -----------------------------------------------------------

  console.log(
    "Docker build environment verified."
  );

  console.log(
    "Starting application build..."
  );


  // -----------------------------------------------------------
  // RUN PNPM BUILD
  //
  // IMPORTANT:
  //
  // All variables from BUILD_ENV are explicitly injected into
  // the pnpm process.
  //
  // BUILD_ENV values override any same-name environment
  // variables inherited by this Node process.
  // -----------------------------------------------------------

  const child = spawn(
    "pnpm",
    ["build"],
    {
      stdio: "inherit",

      env: {
        ...process.env,
        ...buildEnv,
      },
    }
  );


  // -----------------------------------------------------------
  // HANDLE PNPM START ERROR
  // -----------------------------------------------------------

  child.once("error", (error) => {
    console.error(
      "ERROR: Unable to start pnpm build."
    );

    console.error(error.message);

    process.exit(1);
  });


  // -----------------------------------------------------------
  // PROPAGATE PNPM EXIT CODE
  // -----------------------------------------------------------

  child.once("exit", (code, signal) => {
    if (signal) {
      console.error(
        `ERROR: pnpm build terminated by signal ${signal}.`
      );

      process.exit(1);
    }

    process.exit(code ?? 1);
  });
}

main().catch((error) => {
  console.error(
    "ERROR: Unexpected Docker build failure."
  );

  console.error(error.message);

  process.exit(1);
});
NODE


# =============================================================
# PRODUCTION
# =============================================================

FROM node:22-alpine AS runner

WORKDIR /app

RUN corepack enable

ENV NODE_ENV=production

COPY --from=builder /app ./

EXPOSE 3000

CMD ["pnpm", "start"]